// Package app Code generated by swaggo/swag. DO NOT EDIT
package app

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{url_code}/auth/change-password": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Altera a senha do app user autenticado",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Alterar senha do app user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Senhas",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.AppChangePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/auth/forgot-password": {
            "post": {
                "description": "Envia email com link para reset de senha",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Solicitar reset de senha",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Email",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.AppForgotPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.MessageResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/auth/login": {
            "post": {
                "description": "Autentica um app user e retorna token JWT",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Login de app user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Credenciais",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.AppLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.AppAuthResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Invalida o token JWT do app user",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Logout de app user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.MessageResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/auth/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna os dados do app user autenticado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Dados do app user logado",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.AppUserDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/auth/register": {
            "post": {
                "description": "Registra um novo usuário no app do tenant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Registrar app user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados de registro",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.AppRegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/swagger.AppAuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/auth/reset-password": {
            "post": {
                "description": "Reseta a senha usando token recebido por email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Resetar senha",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Token e nova senha",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.AppResetPasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/catalog/products": {
            "get": {
                "description": "Retorna produtos ativos do tenant paginados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "Listar produtos",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Itens por página",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.PaginatedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/catalog/products/{id}": {
            "get": {
                "description": "Retorna detalhes de um produto ativo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "Obter produto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do produto",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.ProductResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/catalog/services": {
            "get": {
                "description": "Retorna serviços ativos do tenant paginados",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "Listar serviços",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Página",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Itens por página",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.PaginatedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/catalog/services/{id}": {
            "get": {
                "description": "Retorna detalhes de um serviço ativo",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Catalog"
                ],
                "summary": "Obter serviço",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID do serviço",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.ServiceResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/profile": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retorna o perfil completo do app user autenticado",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Obter perfil do app user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.AppUserProfileDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Atualiza campos do perfil do app user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Atualizar perfil do app user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Dados do perfil",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/swagger.AppUpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/{url_code}/profile/avatar": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Faz upload da foto de perfil do app user",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Profile"
                ],
                "summary": "Upload de avatar do app user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "URL code do tenant",
                        "name": "url_code",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Imagem do avatar",
                        "name": "avatar",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/swagger.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/swagger.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "swagger.AppAuthResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIs..."
                },
                "user": {
                    "$ref": "#/definitions/swagger.AppUserDTO"
                }
            }
        },
        "swagger.AppChangePasswordRequest": {
            "type": "object",
            "required": [
                "current_password",
                "new_password"
            ],
            "properties": {
                "current_password": {
                    "type": "string",
                    "example": "old_password"
                },
                "new_password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "new_password"
                }
            }
        },
        "swagger.AppForgotPasswordRequest": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                }
            }
        },
        "swagger.AppLoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "password": {
                    "type": "string",
                    "example": "secret123"
                }
            }
        },
        "swagger.AppRegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "john@example.com"
                },
                "name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "secret123"
                }
            }
        },
        "swagger.AppResetPasswordRequest": {
            "type": "object",
            "required": [
                "new_password",
                "token"
            ],
            "properties": {
                "new_password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "new_password"
                },
                "token": {
                    "type": "string",
                    "example": "reset-token-string"
                }
            }
        },
        "swagger.AppUpdateProfileRequest": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string",
                    "example": "Rua A, 123"
                },
                "document": {
                    "type": "string",
                    "example": "123.456.789-00"
                },
                "full_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "notes": {
                    "type": "string",
                    "example": "Some notes"
                },
                "phone": {
                    "type": "string",
                    "example": "+5511999999999"
                }
            }
        },
        "swagger.AppUserDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@example.com"
                },
                "id": {
                    "type": "string",
                    "example": "uuid"
                },
                "name": {
                    "type": "string",
                    "example": "John"
                },
                "profile": {
                    "$ref": "#/definitions/swagger.AppUserProfileDTO"
                },
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "swagger.AppUserProfileDTO": {
            "type": "object",
            "properties": {
                "address": {},
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.jpg"
                },
                "birth_date": {
                    "type": "string",
                    "example": "1990-01-01"
                },
                "document": {
                    "type": "string",
                    "example": "123.456.789-00"
                },
                "full_name": {
                    "type": "string",
                    "example": "John Doe"
                },
                "metadata": {},
                "phone": {
                    "type": "string",
                    "example": "+5511999999999"
                }
            }
        },
        "swagger.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error_message"
                }
            }
        },
        "swagger.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "operation_successful"
                }
            }
        },
        "swagger.PaginatedResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "swagger.ProductResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "A premium widget"
                },
                "id": {
                    "type": "string",
                    "example": "uuid"
                },
                "image_url": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Premium Widget"
                },
                "price": {
                    "type": "number",
                    "example": 29.9
                },
                "sku": {
                    "type": "string",
                    "example": "WDG-001"
                },
                "stock": {
                    "type": "integer",
                    "example": 100
                },
                "tenant_id": {
                    "type": "string",
                    "example": "uuid"
                },
                "translations": {},
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "swagger.ServiceResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string",
                    "example": "1h consulting session"
                },
                "duration": {
                    "type": "integer",
                    "example": 60
                },
                "id": {
                    "type": "string",
                    "example": "uuid"
                },
                "image_url": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "name": {
                    "type": "string",
                    "example": "Consulting"
                },
                "price": {
                    "type": "number",
                    "example": 150
                },
                "tenant_id": {
                    "type": "string",
                    "example": "uuid"
                },
                "translations": {},
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "swagger.UploadResponse": {
            "type": "object",
            "properties": {
                "path": {
                    "type": "string",
                    "example": "/uploads/tenant/file.jpg"
                },
                "public_url": {
                    "type": "string",
                    "example": "http://localhost:8080/uploads/tenant/file.jpg"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "JWT token de autenticação do app user. Formato: Bearer {token}",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "App API",
	Description:      "API pública para usuários finais (app users) dos tenants. Gerencia registro, autenticação, perfil e catálogo de produtos/serviços.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
