-- Drop tables in reverse order of dependencies
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS tenant_app_user_profiles CASCADE;
DROP TABLE IF EXISTS tenant_app_users CASCADE;
DROP TABLE IF EXISTS tenant_settings CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS services CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS tenant_members CASCADE;
DROP TABLE IF EXISTS user_role_permissions CASCADE;
DROP TABLE IF EXISTS user_permissions CASCADE;
DROP TABLE IF EXISTS user_roles CASCADE;
DROP TABLE IF EXISTS user_profiles CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS tenant_profiles CASCADE;
DROP TABLE IF EXISTS tenant_plans CASCADE;
DROP TABLE IF EXISTS tenants CASCADE;
DROP TABLE IF EXISTS saas_plans_promotions CASCADE;
DROP TABLE IF EXISTS promotions CASCADE;
DROP TABLE IF EXISTS saas_features_plans CASCADE;
DROP TABLE IF EXISTS plan_features CASCADE;
DROP TABLE IF EXISTS saas_plans CASCADE;
DROP TABLE IF EXISTS plans CASCADE;
DROP TABLE IF EXISTS saas_features CASCADE;
DROP TABLE IF EXISTS features CASCADE;
DROP TABLE IF EXISTS saas_admin_role_permissions CASCADE;
DROP TABLE IF EXISTS system_admin_role_permissions CASCADE;
DROP TABLE IF EXISTS saas_admin_user_roles CASCADE;
DROP TABLE IF EXISTS system_admin_user_roles CASCADE;
DROP TABLE IF EXISTS saas_admin_permissions CASCADE;
DROP TABLE IF EXISTS system_admin_permissions CASCADE;
DROP TABLE IF EXISTS saas_admin_roles CASCADE;
DROP TABLE IF EXISTS system_admin_roles CASCADE;
DROP TABLE IF EXISTS saas_admin_profiles CASCADE;
DROP TABLE IF EXISTS system_admin_profiles CASCADE;
DROP TABLE IF EXISTS saas_admin_users CASCADE;
DROP TABLE IF EXISTS system_admin_users CASCADE;
DROP TABLE IF EXISTS email_verification_tokens CASCADE;
DROP TABLE IF EXISTS email_templates CASCADE;

-- Drop enums
DROP TYPE IF EXISTS image_variant;
DROP TYPE IF EXISTS media_type;
DROP TYPE IF EXISTS plan_type CASCADE;
DROP TYPE IF EXISTS discount_type CASCADE;
DROP TYPE IF EXISTS storage_provider;
DROP TYPE IF EXISTS user_status CASCADE;
DROP TYPE IF EXISTS billing_cycle;
DROP TYPE IF EXISTS tenant_status;
